#!/usr/bin/env python
import sys

# FIXME: Ideally this is a central entrypoint into crosswind for both conversion directions.
from crosswind.lib2to3.main import main
sys.exit(main("crosswind.lib2to3.fixes"))
