#!/usr/bin/env python2.7
import sys

print ("Checking Python version info..."),
if sys.version_info < (2, 7) or sys.version_info >= (3, 0):
    sys.exit("ERROR: 3to2 requires at least Python 2.7 in the 2.x branch.")
else:
    print ("%d.%d.%d" % (sys.version_info[:3]))

from lib3to2.main import main

sys.exit(main("lib3to2.fixes"))
